# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Java Process 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Java programming, design patterns and enterprise integration. The latest and greatest or, the old and proven. A little bit of everything related to technology, but mostly programming, databases, and sysadmin topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aolarte.github.io" # the base hostname & protocol for your site
twitter_username: aolarte 
github_username:  aolarte 

# Build settings
markdown: kramdown
